sonar.projectKey=selectorshub-enterprise-playwright-automation
sonar.projectName=SelectorsHub Enterprise Playwright Automation
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_0c93ae5ff9b0a918c56cc057159b7802dcc5c5a4

sonar.sourceEncoding=UTF-8

sonar.sources=modules,pages,utils,tests
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.js,tests/**/*.test.js

sonar.exclusions=node_modules/**,playwright-report/**,test-results/**,allure-results/**,allure-report/**,public/**

# Code Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info